# Generated by Django 2.0.2 on 2018-02-11 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('country', models.CharField(choices=[('1', 'Indian'), ('2', 'Other')], max_length=15)),
                ('pincode', models.CharField(blank=True, max_length=15)),
                ('persons', models.ManyToManyField(to='accounts.CompanyPerson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resume')),
                ('verified', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=8)),
                ('year', models.SmallIntegerField()),
                ('cpi', models.FloatField()),
                ('placed_status', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=15)),
                ('parent_name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('category', models.CharField(choices=[('1', 'General'), ('2', 'OBC'), ('3', 'SC'), ('4', 'ST')], max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('jee_air', models.IntegerField()),
                ('hostel_name', models.CharField(blank=True, choices=[('1', 'B1'), ('2', 'B2'), ('3', 'G6'), ('4', 'G5')], max_length=2)),
                ('room_no', models.SmallIntegerField(blank=True)),
                ('hobbies', models.TextField()),
                ('pd_status', models.BooleanField(default=False)),
                ('nationality', models.CharField(choices=[('1', 'Indian'), ('2', 'Other')], max_length=10)),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField()),
                ('x_year', models.SmallIntegerField()),
                ('x_board_name', models.CharField(max_length=30)),
                ('x_percentage', models.CharField(max_length=10)),
                ('xii_year', models.SmallIntegerField()),
                ('xii_board_name', models.CharField(max_length=30)),
                ('xii_percentage', models.CharField(max_length=10)),
                ('ctc', models.IntegerField()),
                ('placed_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.CompanyProfile')),
                ('resumes', models.ManyToManyField(to='accounts.Resume')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
