# Generated by Django 2.0.2 on 2018-02-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180211_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='ctc',
            field=models.IntegerField(blank=True),
        ),
    ]
