# Generated by Django 2.0.2 on 2018-02-11 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='persons',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='resumes',
        ),
        migrations.AddField(
            model_name='companyperson',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='accounts.CompanyProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='accounts.StudentProfile'),
            preserve_default=False,
        ),
    ]
