# Generated by Django 2.0.2 on 2018-02-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_auto_20180211_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobdesig', models.CharField(max_length=30)),
                ('jobdescrip', models.CharField(max_length=50)),
                ('tentativejobloc', models.CharField(max_length=50)),
                ('ads', models.FileField(upload_to='ads')),
                ('bonus', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobdesig', models.CharField(max_length=30)),
                ('jobdescrip', models.CharField(max_length=50)),
                ('tentativejobloc', models.CharField(max_length=50)),
                ('ads', models.FileField(upload_to='ads')),
                ('bonus', models.IntegerField(blank=True)),
            ],
        ),
    ]
