# Generated by Django 2.0.2 on 2018-02-26 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180226_1507'),
        ('company', '0003_internoffer_joboffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=64)),
                ('usable', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='internoffer',
            name='company',
            field=models.ForeignKey(blank=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='internoffer', to='accounts.CompanyProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joboffer',
            name='company',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='joboffer', to='accounts.CompanyProfile'),
            preserve_default=False,
        ),
    ]
