# Generated by Django 2.0.2 on 2018-02-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('country', models.CharField(choices=[('1', 'Indian'), ('2', 'Other')], max_length=15)),
                ('pincode', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
