# Generated by Django 2.0.2 on 2018-02-26 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20180226_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internoffer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internoffer', to='accounts.CompanyProfile'),
        ),
    ]
