# Generated by Django 2.0.2 on 2018-02-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rollno', models.CharField(max_length=8)),
                ('year', models.SmallIntegerField()),
                ('cpi', models.FloatField()),
                ('placed_company', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('parent_name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('category', models.CharField(choices=[('1', 'General'), ('2', 'OBC'), ('3', 'SC'), ('4', 'ST')], max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('jee_air', models.IntegerField()),
                ('hostel_name', models.CharField(blank=True, choices=[('1', 'B1'), ('2', 'B2'), ('3', 'G6'), ('4', 'G5')], max_length=2)),
                ('room_no', models.SmallIntegerField(blank=True)),
                ('hobbies', models.TextField()),
                ('pd_status', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=3)),
                ('nationality', models.CharField(choices=[('1', 'Indian'), ('2', 'Other')], max_length=10)),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField()),
                ('x_year', models.SmallIntegerField()),
                ('x_board_name', models.CharField(max_length=30)),
                ('x_percentage', models.CharField(max_length=10)),
                ('xii_year', models.SmallIntegerField()),
                ('xii_board_name', models.CharField(max_length=30)),
                ('xii_percentage', models.CharField(max_length=10)),
                ('resumes', models.FileField(blank=True, upload_to='media')),
                ('ctc', models.IntegerField()),
            ],
        ),
    ]
